/**
 * Module 03: Opening DM — Marco framework before phone capture.
 * Reply text is generated by one guided Haiku pass (full thread); stage moves forward
 * with a light state helper so the exclusivity loop still resolves deterministically.
 */
import type { Conversation, Lead, Message } from "../../core/types.js";
import { FunnelStage } from "../../core/state.js";
import {
  leadTextSignalsNoAgent,
  threadContainsAgentQuestion,
} from "../../app/conversationUtils.js";
import {
  extractPhone,
  extractPhoneFromConversation,
  PHONE_JUST_CAPTURED_REPLY,
} from "../../app/funnelDeterministic.js";
import type { MarcoLogContext } from "../../app/marcoLog.js";
import { generateMarcoOpeningReply } from "../../integrations/llm/index.js";

export interface ModuleResult {
  lead: Lead;
  reply: string | null;
}

export interface OpeningProcessOptions {
  /**
   * True only when the lead repeated their own line (deterministic). Controls funnel advance.
   * Must NOT be set for "Marco duplicated himself" — that would freeze the opening stage and cause loops.
   */
  leadRepeatedForAdvancement: boolean;
  /** Lead repeat signal for the model JSON (includes Haiku-detected near-duplicate lead lines). */
  leadLineRepeatForModel: boolean;
  coachingNote: string;
  /** Instagram comment vs DM — shapes LLM context for short listing questions. */
  inboundChannel?: "comment" | "dm";
  inboundPlatform?: string;
  log?: MarcoLogContext;
}

function saysHasAgent(text: string): boolean {
  const t = text.toLowerCase();
  if (!/\bagent\b/.test(t)) return false;
  return /\b(i am|i'm|yes|yeah|yep|already|currently|working with|have)\b/.test(t);
}

function openToAdvisor(text: string): boolean {
  const t = text.toLowerCase();
  return /\b(open|maybe|i guess|sure|okay|ok|possibly|interview)\b/.test(t);
}

function getLastUserMessage(conversation: Conversation): Message | null {
  const reversed = [...conversation.messages].reverse();
  return reversed.find((m) => m.role === "user") ?? null;
}

/** Phone in thread (e.g. IG contact card echo) — must advance even when ManyChat sends the same line twice. */
function capturablePhoneFromThread(
  conversation: Conversation,
  lastUserText: string,
): string | null {
  return extractPhone(lastUserText) ?? extractPhoneFromConversation(conversation) ?? null;
}

/**
 * After this turn's outbound, where the funnel should sit before the next inbound.
 * Repeat turns do not advance. Agent + not open stays in OpeningOfferedDetails for exclusivity ask.
 */
function nextOpeningState(
  lead: Lead,
  lastUserText: string,
  repeat: boolean,
  conversation: Conversation,
): FunnelStage {
  if (capturablePhoneFromThread(conversation, lastUserText)) {
    return FunnelStage.PhoneRequested;
  }
  if (lead.state === FunnelStage.New) {
    return FunnelStage.OpeningAskedFirstTime;
  }
  if (lead.state === FunnelStage.OpeningAskedFirstTime) {
    if (repeat) return FunnelStage.OpeningAskedFirstTime;
    return FunnelStage.OpeningOfferedDetails;
  }
  if (lead.state === FunnelStage.OpeningOfferedDetails) {
    /** Deterministic escape: agent Q already in thread + lead said no agent — always advance (never freeze on repeat). */
    if (threadContainsAgentQuestion(conversation) && leadTextSignalsNoAgent(lastUserText)) {
      return FunnelStage.PhoneRequested;
    }
    if (repeat) return FunnelStage.OpeningOfferedDetails;
    if (saysHasAgent(lastUserText) && !openToAdvisor(lastUserText)) {
      return FunnelStage.OpeningOfferedDetails;
    }
    return FunnelStage.PhoneRequested;
  }
  return lead.state;
}

export async function process(
  lead: Lead,
  conversation: Conversation,
  options?: OpeningProcessOptions,
): Promise<ModuleResult> {
  const last = getLastUserMessage(conversation);
  if (!last) {
    return { lead, reply: null };
  }

  if (
    lead.state !== FunnelStage.New &&
    lead.state !== FunnelStage.OpeningAskedFirstTime &&
    lead.state !== FunnelStage.OpeningOfferedDetails
  ) {
    return { lead, reply: null };
  }

  const openingStage = lead.state;
  const repeat = Boolean(options?.leadRepeatedForAdvancement && lead.state !== FunnelStage.New);

  const phoneDigits = lead.phone ?? capturablePhoneFromThread(conversation, last.text);
  if (phoneDigits) {
    const justCaptured = !lead.phone;
    return {
      lead: { ...lead, phone: phoneDigits, state: FunnelStage.PropertySent },
      reply: justCaptured ? PHONE_JUST_CAPTURED_REPLY : null,
    };
  }

  const note = options?.coachingNote?.trim() ?? "";
  const preflight = {
    repeatedMessage: Boolean(options?.leadLineRepeatForModel),
    coachingNote: note,
  };

  const reply = await generateMarcoOpeningReply({
    lead,
    conversation,
    openingStage,
    preflight,
    inboundChannel: options?.inboundChannel ?? "dm",
    inboundPlatform: options?.inboundPlatform ?? lead.platform,
    log: options?.log,
  });

  const nextState = nextOpeningState(lead, last.text, repeat, conversation);

  return {
    lead: { ...lead, state: nextState },
    reply,
  };
}
