/**
 * Module 03: Opening DM — Marco framework before phone capture.
 * Reply text is generated by one guided Haiku pass (full thread); stage moves forward
 * with a light state helper so the exclusivity loop still resolves deterministically.
 */
import type { Conversation, Lead, Message } from "../../core/types.js";
import { FunnelStage } from "../../core/state.js";
import {
  leadTextSignalsNoAgent,
  threadContainsAgentQuestion,
} from "../../app/conversationUtils.js";
import {
  extractPhone,
  extractPhoneFromConversation,
  PHONE_JUST_CAPTURED_REPLY,
} from "../../app/funnelDeterministic.js";
import type { MarcoLogContext } from "../../app/marcoLog.js";
import { generateMarcoOpeningReply } from "../../integrations/llm/index.js";

export interface ModuleResult {
  lead: Lead;
  reply: string | null;
}

export interface OpeningProcessOptions {
  /**
   * True only when the lead repeated their own line (deterministic). Controls funnel advance.
   * Must NOT be set for "Marco duplicated himself" — that would freeze the opening stage and cause loops.
   */
  leadRepeatedForAdvancement: boolean;
  /** Lead repeat signal for the model JSON (includes Haiku-detected near-duplicate lead lines). */
  leadLineRepeatForModel: boolean;
  coachingNote: string;
  /** Instagram comment vs DM — shapes LLM context for short listing questions. */
  inboundChannel?: "comment" | "dm";
  inboundPlatform?: string;
  log?: MarcoLogContext;
}

function saysHasAgent(text: string): boolean {
  const t = text.toLowerCase();
  if (!/\bagent\b/.test(t)) return false;
  return /\b(i am|i'm|yes|yeah|yep|already|currently|working with|have)\b/.test(t);
}

function openToAdvisor(text: string): boolean {
  const t = text.toLowerCase();
  return /\b(open|maybe|i guess|sure|okay|ok|possibly|interview)\b/.test(t);
}

function getLastUserMessage(conversation: Conversation): Message | null {
  const reversed = [...conversation.messages].reverse();
  return reversed.find((m) => m.role === "user") ?? null;
}

/** Phone in thread (e.g. IG contact card echo) — must advance even when ManyChat sends the same line twice. */
function capturablePhoneFromThread(
  conversation: Conversation,
  lastUserText: string,
): string | null {
  return extractPhone(lastUserText) ?? extractPhoneFromConversation(conversation) ?? null;
}

/**
 * After this turn's outbound, where the funnel should sit before the next inbound.
 * Repeat turns do not advance. Agent + not open stays in OpeningOfferedDetails for exclusivity ask.
 */
function nextOpeningState(
  lead: Lead,
  lastUserText: string,
  repeat: boolean,
  conversation: Conversation,
): FunnelStage {
  if (capturablePhoneFromThread(conversation, lastUserText)) {
    return FunnelStage.PhoneRequested;
  }

  /* ── COLLAPSED OPENER (Aug 2026) ────────────────────────────────────────
     The opener used to be a three-beat ladder: ask the first-time-buyer
     question, wait; offer the breakdown, wait; ask for the number, wait.
     Three round trips before a phone number ever landed.

     Kendrick's TikTok threads on Wesley's account (the screenshots this was
     modelled on) get there in ONE: value plus options plus the number ask in
     the first message. That matters because the observed gaps between DM
     turns are DAYS, not minutes, so every extra beat is a real chance to
     lose the lead entirely rather than a small delay.

     So the first outbound now carries the ask, and the funnel goes straight
     to PhoneRequested, where 04-phone-extraction takes over.

     Legacy stages still resolve: leads that were mid-ladder when this
     shipped advance rather than being stranded waiting for a beat that no
     longer exists. The one thing preserved from the old ladder is the
     has-an-agent hold, which is a real objection and not a pacing step. */
  if (
    lead.state === FunnelStage.New ||
    lead.state === FunnelStage.OpeningAskedFirstTime ||
    lead.state === FunnelStage.OpeningOfferedDetails
  ) {
    /* Deterministic escape kept from the old ladder: agent question already
       asked and answered "no agent" always advances, never freezes. */
    if (threadContainsAgentQuestion(conversation) && leadTextSignalsNoAgent(lastUserText)) {
      return FunnelStage.PhoneRequested;
    }
    /* A lead who says they already have an agent is a genuine objection, so
       hold the opening phase and let the reply address it. Not a pacing
       beat, which is why it survives the collapse. */
    if (saysHasAgent(lastUserText) && !openToAdvisor(lastUserText)) {
      return FunnelStage.OpeningOfferedDetails;
    }
    /* A repeated message means the lead said nothing new; re-asking the
       number on a loop reads as nagging, so hold position. */
    if (repeat && lead.state !== FunnelStage.New) {
      return lead.state;
    }
    return FunnelStage.PhoneRequested;
  }
  return lead.state;
}

export async function process(
  lead: Lead,
  conversation: Conversation,
  options?: OpeningProcessOptions,
): Promise<ModuleResult> {
  const last = getLastUserMessage(conversation);
  if (!last) {
    return { lead, reply: null };
  }

  if (
    lead.state !== FunnelStage.New &&
    lead.state !== FunnelStage.OpeningAskedFirstTime &&
    lead.state !== FunnelStage.OpeningOfferedDetails
  ) {
    return { lead, reply: null };
  }

  const openingStage = lead.state;
  const repeat = Boolean(options?.leadRepeatedForAdvancement && lead.state !== FunnelStage.New);

  const phoneDigits = lead.phone ?? capturablePhoneFromThread(conversation, last.text);
  if (phoneDigits) {
    const justCaptured = !lead.phone;
    return {
      lead: { ...lead, phone: phoneDigits, state: FunnelStage.PropertySent },
      reply: justCaptured ? PHONE_JUST_CAPTURED_REPLY : null,
    };
  }

  const note = options?.coachingNote?.trim() ?? "";
  const preflight = {
    repeatedMessage: Boolean(options?.leadLineRepeatForModel),
    coachingNote: note,
  };

  const reply = await generateMarcoOpeningReply({
    lead,
    conversation,
    openingStage,
    preflight,
    inboundChannel: options?.inboundChannel ?? "dm",
    inboundPlatform: options?.inboundPlatform ?? lead.platform,
    log: options?.log,
  });

  const nextState = nextOpeningState(lead, last.text, repeat, conversation);

  return {
    lead: { ...lead, state: nextState },
    reply,
  };
}
